### ISSUE TITLE
vivo y81解锁失败

### ISSUE THREAD

**Issue by MCredbear** [Mintimate/Vivo_unlock#1]
![图片](https://user-images.githubusercontent.com/40625974/60959162-5621d800-a33a-11e9-89da-f3b927d8b4ae.png)
这玩意的处理器是联fxxk的，2018年上市

还有你这个fastboot也是从别处clone的吧？

**Comment by Mintimate** [comment]
这个fastboot是早些年，根据xda上流出fastboot bbk unlock vivo做的；现在对Android 6.0（包括Android 6）都没有用。
